colors:
- hex: '#36291B'
  id: 1
- hex: '#E3FBD3'
  id: 2
- hex: '#03A6C7'
  id: 3
- hex: '#7E90E4'
  id: 4
- hex: '#A1649F'
  id: 5
- hex: '#D18659'
  id: 6
- hex: '#23FAA3'
  id: 7
- hex: '#9C5671'
  id: 8
- hex: '#3F2999'
  id: 9
- hex: '#D3E041'
  id: 10
- hex: '#1D67FA'
  id: 11
- hex: '#B28454'
  id: 12
- hex: '#F13521'
  id: 13
- hex: '#59D6D3'
  id: 14
- hex: '#3E8CC9'
  id: 15
- hex: '#BB824E'
  id: 16
- hex: '#D3C942'
  id: 17
- hex: '#789387'
  id: 18
- hex: '#9B7E64'
  id: 19
- hex: '#3CC124'
  id: 20
- hex: '#349FD8'
  id: 21
- hex: '#82084E'
  id: 22
- hex: '#3B569E'
  id: 23
- hex: '#4EE75F'
  id: 24
- hex: '#20F05F'
  id: 25
- hex: '#4A7F8E'
  id: 26
- hex: '#ABA18E'
  id: 27
- hex: '#5349F7'
  id: 28
- hex: '#AC5EF9'
  id: 29
- hex: '#AEA588'
  id: 30
- hex: '#512E8D'
  id: 31
- hex: '#184174'
  id: 32
- hex: '#A9A961'
  id: 33
- hex: '#1C2190'
  id: 34
- hex: '#D42F8C'
  id: 35
- hex: '#F8F43F'
  id: 36
- hex: '#7C180B'
  id: 37
- hex: '#4D39AC'
  id: 38
- hex: '#0626D8'
  id: 39
- hex: '#F74180'
  id: 40
- hex: '#A02AC9'
  id: 41
- hex: '#9C8554'
  id: 42
- hex: '#FB5510'
  id: 43
- hex: '#3C4A96'
  id: 44
- hex: '#20AD4F'
  id: 45
- hex: '#C3407E'
  id: 46
- hex: '#71C6F3'
  id: 47
- hex: '#DCEABE'
  id: 48
- hex: '#A08C4D'
  id: 49
- hex: '#523A57'
  id: 50
- hex: '#68013C'
  id: 51
- hex: '#944905'
  id: 52
- hex: '#A9C166'
  id: 53
- hex: '#076859'
  id: 54
- hex: '#51E70D'
  id: 55
- hex: '#E362C7'
  id: 56
- hex: '#6A361C'
  id: 57
- hex: '#98315A'
  id: 58
- hex: '#E3E9EB'
  id: 59
- hex: '#3A05FC'
  id: 60
- hex: '#398CA7'
  id: 61
- hex: '#19C409'
  id: 62
- hex: '#620B99'
  id: 63
- hex: '#1829A2'
  id: 64
- hex: '#BA05B0'
  id: 65
- hex: '#12734E'
  id: 66
- hex: '#A5926C'
  id: 67
- hex: '#113662'
  id: 68
- hex: '#C05A00'
  id: 69
- hex: '#91EF89'
  id: 70
- hex: '#18CC4E'
  id: 71
- hex: '#8BDC26'
  id: 72
- hex: '#B04043'
  id: 73
- hex: '#F4E147'
  id: 74
- hex: '#2D92E6'
  id: 75
- hex: '#C90693'
  id: 76
- hex: '#0B2C72'
  id: 77
- hex: '#975274'
  id: 78
- hex: '#50AC6E'
  id: 79
- hex: '#5F92DB'
  id: 80
- hex: '#F38772'
  id: 81
- hex: '#D5D2A1'
  id: 82
- hex: '#3936ED'
  id: 83
- hex: '#6C94BC'
  id: 84
- hex: '#B75F98'
  id: 85
- hex: '#71B1C0'
  id: 86
- hex: '#3FFC80'
  id: 87
- hex: '#5C8332'
  id: 88
- hex: '#DEB57D'
  id: 89
- hex: '#7CA2DA'
  id: 90
- hex: '#BF8B13'
  id: 91
- hex: '#B0E677'
  id: 92
- hex: '#0E4B02'
  id: 93
- hex: '#2B2ACB'
  id: 94
- hex: '#42BF1E'
  id: 95
- hex: '#277A9E'
  id: 96
- hex: '#79A6AF'
  id: 97
- hex: '#A836D4'
  id: 98
- hex: '#DD6299'
  id: 99
- hex: '#83B8B2'
  id: 100
